### ISSUE TITLE
new logo/icon

### ISSUE THREAD

**Issue by mansya** [DroidsOnRoids/android-device-cleaner#10]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by koral--** [comment]
Great idea. Feel free to create a pull request.

**Comment by mansya** [comment]
I have design a logo for this project. what do you think ? do you like it ?
![android device cleaner](https://user-images.githubusercontent.com/33461607/42432452-cb301b16-8374-11e8-9de6-92c18e75c8cd.png)

**Comment by mansya** [comment]
I have upload all file to this link 
https://drive.google.com/open?id=13kojDsiZYtDZViAEPTpxaSrCoVBT4Spa

And I have sent you pull requests. please check

**Comment by koral--** [comment]
Thanks, logo added in https://github.com/DroidsOnRoids/android-device-cleaner/pull/11
